package system.utilities.languageManager;

import org.jetbrains.annotations.Contract;

public enum MessageKeys {

    /* Related to Ticket Control Panel & Ticket Message*/

    EMPTY("EMPTY"),
    UNDERMAINTENANCEMODE("UNDERMAINTENANCEMODE"),
    NOPERMISSIONS("NOPERMISSIONS"),
    TICKET_CLOSE_ERRORMESSAGE("TICKET-CLOSE-ERRORMESSAGE"),

    /* Embed Ticket message */

    TICKET_MESSAGE_TITLE("TICKET-MESSAGE-TITLE"),
    TICKET_MESSAGE_DESCRIPTION("TICKET-MESSAGE-DESCRIPTION"),
    TICKET_MESSAGE_FLOOR("TICKET-MESSAGE-FLOOR"),
    TICKET_MESSAGE_FLOOR_ICON("TICKET-MESSAGE-FLOOR-ICON"),

    /* Check out embed message */

    TICKET_CHECKOUT_TITLE("TICKET_CHECKOUT_TITLE"),
    TICKET_CHECKOUT_DESCRIPTION("TICKET_CHECKOUT_DESCRIPTION"),
    TICKET_CHECKOUT_SELECTION_PAYPAL("TICKET_CHECKOUT_SELECTION_PAYPAL"),
    TICKET_CHECKOUT_SELECTION_BITCOINS("TICKET_CHECKOUT_SELECTION_BITCOINS"),
    TICKET_CHECKOUT_SELECTION_CASHAPP("TICKET_CHECKOUT_SELECTION_CASHAPP"),
    TICKET_CHECKOUT_FLOOR("TICKET_CHECKOUT_FLOOR"),
    TICKET_CHECKOUT_DESCRIPTION_SELECTED("TICKET_CHECKOUT_DESCRIPTION-SELECTED"),

    /* Stats cart embed message */
    TICKET_CART_STATS_TITLE("TICKET_CART_STATS_TITLE"),
    TICKET_CART_STATS_DESCRIPTION("TICKET_CART_STATS_DESCRIPTION"),
    TICKET_CART_STATS_ERROR("TICKET_CART_STATS_ERROR"),


    /* Embed Ticket Control panel*/

    TICKET_CONTROLPANEL_COLOR("TICKET-CONTROLPANEL-COLOR"),
    TICKET_CONTROLPANEL_DESCRIPTION_CATEGORY("TICKET-CONTROLPANEL-DESCRIPTION-CATEGORY"),
    TICKET_CONTROLPANEL_DESCRIPTION_CHANNEL("TICKET-CONTROLPANEL-DESCRIPTION-CHANNEL"),
    TICKET_CONTROLPANEL_DESCRIPTION_MESSAGE("TICKET-CONTROLPANEL-DESCRIPTION-MESSAGE"),
    TICKET_CONTROLPANEL_DESCRIPTION_MISS_MESSAGE("TICKET-CONTROLPANEL-DESCRIPTION-MISS-MESSAGE"),

    TICKET_CONTROLPANEL_TICKETMANAGER_DESCRIPTION_NOTE("TICKET-CONTROLPANEL-TICKETMANAGER-DESCRIPTION-NOTE"),
    TICKET_CONTROLPANEL_TICKETMANAGER_DESCRIPTION_CATEGORY_CHANGE("TICKET-CONTROLPANEL-TICKETMANAGER-DESCRIPTION-CATEGORY-CHANGE"),
    TICKET_CONTROLPANEL_TICKETMANAGER_DESCRIPTION_CHANNEL_CHANGE("TICKET-CONTROLPANEL-TICKETMANAGER-DESCRIPTION-CHANNEL-CHANGE"),
    TICKET_CONTROLPANEL_TICKETMANAGER_DESCRIPTION_UNDERMAINTENANCEMODE("TICKET-CONTROLPANEL-TICKETMANAGER-DESCRIPTION-UNDERMAINTENANCEMODE"),
    TICKET_CONTROLPANEL_TICKETMANAGER_CHANNELCHANGING_DESCRIPTION("TICKET-CONTROLPANEL-TICKETMANAGER-CHANNELCHANGING-DESCRIPTION"),
    TICKET_CONTROLPANEL_TICKETMANAGER_CHANNELCHANGING_WRONGMESSAGE("TICKET-CONTROLPANEL-TICKETMANAGER-CHANNELCHANGE-WRONGMESSAGE"),

    TICKET_CONTROLPANEL_TICKETHISTORY_DESCRIPTION_TOTALTICKETS("TICKET-CONTROLPANEL-TICKETHISTORY-DESCRIPTION-TOTALTICKETS"),
    TICKET_CONTROLPANEL_TICKETHISTORY_DESCRIPTION_TICKETACCEPTED("TICKET-CONTROLPANEL-TICKETHISTORY-DESCRIPTION-TICKETACCEPTED"),
    TICKET_CONTROLPANEL_TICKETHISTORY_DESCRIPTION_TICKETDENIED("TICKET-CONTROLPANEL-TICKETHISTORY-DESCRIPTION-TICKETDENIED"),
    TICKET_CONTROLPANEL_TICKETHISTORY_DESCRIPTION_TICKETHOLD("TICKET-CONTROLPANEL-TICKETHISTORY-DESCRIPTION-TICKETHOLD"),

    TICKET_CONTORLPANEL_FLOOR("TICKET-CONTORLPANEL-FLOOR"),
    TICKET_CONTORLPANEL_FLOOR_ICON("TICKET-CONTORLPANEL-FLOOR-ICON"),

    /* Private Message */

    PRIVATE_WARN_CHANNEL_OWNERSHIP_TITLE("PRIVATE-WARN-CHANNEL-OWNERSHIP-TITLE"),
    PRIVATE_WARN_CHANNEL_OWNERSHIP_DESCRIPTION("PRIVATE-WARN-CHANNEL-OWNERSHIP-DESCRIPTION"),
    PRIVATE_WARN_CHANNEL_OWNERSHIP_FLOOR("PRIVATE-WARN-CHANNEL-OWNERSHIP-FLOOR"),

    PRIVATE_WARN_MESSAGE_OWNERSHIP_TITLE("PRIVATE-WARN-MESSAGE-OWNERSHIP-TITLE"),
    PRIVATE_WARN_MESSAGE_OWNERSHIP_DESCRIPTION("PRIVATE-WARN-MESSAGE-OWNERSHIP-DESCRIPTION"),
    PRIVATE_WARN_MESSAGE_OWNERSHIP_FLOOR("PRIVATE-WARN-MESSAGE-OWNERSHIP-FLOOR"),

    PRIVATE_TICKET_CREATOR_DELETED_EMBED_TITLE("PRIVATE-TICKET-CREATOR-DELETED-EMBED-TITLE"),
    PRIVATE_TICKET_CREATOR_DELETED_EMBED_DESCRIPTION("PRIVATE-TICKET-CREATOR-DELETED-EMBED-DESCRIPTION"),
    PRIVATE_TICKET_CREATOR_DELETED_EMBED_FLOOR("PRIVATE-TICKET-CREATOR-DELETED-EMBED-FLOOR"),

    PRIVATE_TICKET_CREATOR_CLOSE_EMBED_TITLE("PRIVATE-TICKET-CREATOR-CLOSE-EMBED-TITLE"),
    PRIVATE_TICKET_CREATOR_CLOSE_EMBED_DESCRIPTION("PRIVATE-TICKET-CREATOR-CLOSE-EMBED-DESCRIPTION"),
    PRIVATE_TICKET_CREATOR_CLOSE_EMBED_FLOOR("PRIVATE-TICKET-CREATOR-CLOSE-EMBED-FLOOR"),

    PRIVATE_TICKET_DELETED_EMBED_TITLE("PRIVATE-TICKET-DELETED-EMBED-TITLE"),
    PRIVATE_TICKET_DELETED_EMBED_DESCRIPTION("PRIVATE-TICKET-DELETED-EMBED-DESCRIPTION"),
    PRIVATE_TICKET_DELETED_EMBED_FLOOR("PRIVATE-TICKET-DELETED-EMBED-FLOOR"),

    /* Ticket Open Embed Source */
    TICKET_OPEN_TITLE("TICKET-OPEN-TITLE"),
    TICKET_OPEN_DESCRIPTION_UNSELECTED("TICKET-OPEN-DESCRIPTION-UNSELECTED"),
    TICKET_OPEN_DESCRIPTION_SELECTED("TICKET-OPEN-DESCRIPTION-SELECTED"),
    TICKET_OPEN_DESCRIPTION_BUNDLE("TICKET-OPEN-DESCRIPTION-BUNDLE"),
    TICKET_OPEN_DESCRIPTION_PRODUCTS("TICKET-OPEN-DESCRIPTION-PRODUCTS"),
    TICKET_OPEN_FLOOR("TICKET-OPEN-FLOOR"),
    TICKET_OPEN_JUMPMESSAGE("TICKET-OPEM-JUMPMESSAGE"),

    /* Shop Bundle */
    TICKET_BUNDLE_BOTS_NAME("TICKET-BUNDLE-BOTS-NAME"),
    TICKET_BUNDLE_BOTS_DESCRIPTION("TICKET-BUNDLE-BOTS-DESCRIPTION"),
    TICKET_BUNDLE_BOTS_EMOJI("TICKET-BUNDLE-BOTS-EMOJI"),

    TICKET_BUNDLE_BOOSTER_NAME("TICKET-BUNDLE-BOOSTER-NAME"),
    TICKET_BUNDLE_BOOSTER_DESCRIPTION("TICKET-BUNDLE-BOOSTER-DESCRIPTION"),
    TICKET_BUNDLE_BOOSTER_EMOJI("TICKET-BUNDLE-BOOSTER-EMOJI"),

    TICKET_BUNDLE_BOTS_PRODUCT_PROTECTION_NAME("TICKET-BUNDLE-BOTS-PRODUCT-PROTECTION-NAME"),
    TICKET_BUNDLE_BOTS_PRODUCT_PROTECTION_DESCRIPTION("TICKET-BUNDLE-BOTS-PRODUCT-PROTECTION-DESCRIPTION"),
    TICKET_BUNDLE_BOTS_PRODUCT_PROTECTION_EMOJI("TICKET-BUNDLE-BOTS-PRODUCT-PROTECTION-EMOJI"),

    TICKET_BUNDLE_BOTS_PRODUCT_MUSIC_NAME("TICKET-BUNDLE-BOTS-PRODUCT-MUSIC-NAME"),
    TICKET_BUNDLE_BOTS_PRODUCT_MUSIC_DESCRIPTION("TICKET-BUNDLE-BOTS-PRODUCT-MUSIC-DESCRIPTION"),
    TICKET_BUNDLE_BOTS_PRODUCT_MUSIC_EMOJI("TICKET-BUNDLE-BOTS-PRODUCT-MUSIC-EMOJI"),

    TICKET_BUNDLE_BOOSTER_PRODUCT_1MONTH_2_NAME("TICKET-BUNDLE-BOOSTER-PRODUCT-1MONTH-2-NAME"),
    TICKET_BUNDLE_BOOSTER_PRODUCT_1MONTH_7_NAME("TICKET-BUNDLE-BOOSTER-PRODUCT-1MONTH-7-NAME"),
    TICKET_BUNDLE_BOOSTER_PRODUCT_1MONTH_14_NAME("TICKET-BUNDLE-BOOSTER-PRODUCT-1MONTH-14-NAME"),

    TICKET_BUNDLE_BOOSTER_PRODUCT_3MONTH_2_NAME("TICKET-BUNDLE-BOOSTER-PRODUCT-3MONTH-2-NAME"),
    TICKET_BUNDLE_BOOSTER_PRODUCT_3MONTH_7_NAME("TICKET-BUNDLE-BOOSTER-PRODUCT-3MONTH-7-NAME"),
    TICKET_BUNDLE_BOOSTER_PRODUCT_3MONTH_14_NAME("TICKET-BUNDLE-BOOSTER-PRODUCT-3MONTH-14-NAME"),
    ;

    private final String key;

    MessageKeys(String key) {
        this.key = key;
    }

    @Contract(pure = true)
    public String getKey() {
        return key;
    }

}
